In [2]:
import pandas as pd
from sqlalchemy import create_engine

# # --------------------------------------------------
# # Logging Configuration
# # --------------------------------------------------
# logging.basicConfig(
#     filename="logs/ingestion_db.log",
#     level=logging.DEBUG,
#     format="%(asctime)s - %(levelname)s - %(message)s",
#     filemode="a"
# )

# --------------------------------------------------
# Database Engine
# --------------------------------------------------
username = "postgres"
password = "akasmik"
host = "localhost"
port = "5432"
database = "Inventory_vendor"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)
try:
    with engine.connect() as conn:
        print("connection successful !")
except Exception as e:
    print("Connection failed")
    print(e)

connection successful !

In [2]:
df_tables = pd.read_sql(
"""
SELECT table_name 
FROM information_schema.tables
WHERE table_schema = 'public'
""",engine)
print(df_tables)

        table_name
0            sales
1  purchase_prices
2   vendor_invoice
3  begin_inventory
4    end_inventory
5        purchases

In [3]:
purchases_rowCnt = pd.read_sql("select count(*) from purchases",engine);
print(purchases_rowCnt)

     count
0  1650000

In [7]:
for table in df_tables['table_name']:
    print('-' * 50, table, '-' * 50)
    
    df_count = pd.read_sql(f"SELECT COUNT(*) AS count FROM {table}", engine)
    count = df_count['count'].values[0]
    
    print('Count of records:', count)
    display(pd.read_sql(f"select * from {table} limit 5",engine))

-------------------------------------------------- sales --------------------------------------------------
Count of records: 1282536

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,15_WANBORNE_4181,15,4181,Calypso Spiced Rum,1.75L,1,11.99,11.99,2024-01-31,1750.0,1,1.84,660,SAZERAC NORTH AMERICA INC.
1,21_BALERNO_5713,21,5713,DeKuyper Sour Apple Pucker,1.75L,1,14.99,14.99,2024-01-29,1750.0,1,1.84,12546,JIM BEAM BRANDS COMPANY
2,11_CARDEND_25704,11,25704,Murphy-Goode Chard Sonoma,750mL,2,29.98,14.99,2024-01-22,750.0,2,0.22,9552,M S WALKER INC
3,15_WANBORNE_3362,15,3362,Poland Spring Gin,Liter,6,35.94,5.99,2024-01-21,1000.0,1,6.3,9552,M S WALKER INC
4,15_WANBORNE_2120,15,2120,Canadian Club,1.75L,12,191.88,15.99,2024-01-30,1750.0,1,22.05,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 1650000

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

In [10]:
vendor_specific_purchases_data = pd.read_sql_query('select * from purchases where "VendorNumber" = 4466',engine)
vendor_specific_purchases_data

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1617,8_ALNERWICK_3140,8,3140,TGI Fridays Orange Dream,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11993,2024-09-07,2024-09-15,2024-09-25,2024-10-23,11.19,5,55.95,1
1618,44_PORTHCRAWL_5255,44,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11993,2024-09-07,2024-09-13,2024-09-25,2024-10-23,9.35,6,56.10,1
1619,14_BROMWICH_5215,14,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11993,2024-09-07,2024-09-12,2024-09-25,2024-10-23,9.41,6,56.46,1
1620,15_WANBORNE_5255,15,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11993,2024-09-07,2024-09-15,2024-09-25,2024-10-23,9.35,6,56.10,1
1621,38_GOULCREST_3140,38,3140,TGI Fridays Orange Dream,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11993,2024-09-07,2024-09-13,2024-09-25,2024-10-23,11.19,5,55.95,1

In [11]:
vendor_specific_purchasePrices_data = pd.read_sql_query('select * from purchase_prices where "VendorNumber" = 4466',engine)
vendor_specific_purchasePrices_data

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [12]:
vendor_specific_vendorInvoid_data = pd.read_sql_query('select * from vendor_invoice where "VendorNumber" = 4466',engine)
vendor_specific_vendorInvoid_data

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [15]:
vendor_specific_sales_data = pd.read_sql_query("""select * from sales where "VendorNo" = '4466'""",engine)
vendor_specific_sales_data

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,2,25.98,12.99,2024-01-15,1750.0,1,3.67,4466,AMERICAN VINTAGE BEVERAGE
1,14_BROMWICH_5215,14,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-30,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,10_HORNSEY_5215,10,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-14,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,10_HORNSEY_5255,10,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-01-30,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,23_ARBINGTON_5255,23,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-01-14,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,73_DONCASTER_5215,73,5215,TGI Fridays Long Island Iced,1.75L,2,25.98,12.99,2024-12-10,1750.0,1,3.67,4466,AMERICAN VINTAGE BEVERAGE
991,74_PAENTMARWY_3140,74,3140,TGI Fridays Orange Dream,1.75L,1,12.99,12.99,2024-12-11,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
992,74_PAENTMARWY_5255,74,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-20,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
993,8_ALNERWICK_5215,8,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-30,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
994,8_ALNERWICK_5215,8,5215,TGI Fridays Long Island Iced,1.75L,2,25.98,12.99,2024-12-11,1750.0,1,3.67,4466,AMERICAN VINTAGE BEVERAGE

In [16]:
vendor_specific_purchases_data.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              3756  42029.64
5215  9.41               3840  36134.40
5255  9.35               4721  44141.35

In [17]:
vendor_specific_vendorInvoid_data['PONumber'].nunique()

55

In [18]:
vendor_specific_vendorInvoid_data.shape

(55, 10)

In [19]:
vendor_specific_vendorInvoid_data.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [24]:
vendor_specific_sales_data['SalesDollars'] = pd.to_numeric(vendor_specific_sales_data['SalesDollars'], errors='coerce')
vendor_specific_sales_data['SalesPrice'] = pd.to_numeric(vendor_specific_sales_data['SalesPrice'], errors='coerce')
vendor_specific_sales_data['SalesQuantity'] = pd.to_numeric(vendor_specific_sales_data['SalesQuantity'], errors='coerce')
vendor_specific_sales_data.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140        4793.31     3013.68            369
5215        6819.75     4780.32            525
5255        8690.31     5131.05            669

In [25]:
vendor_specific_vendorInvoid_data.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [30]:
freight_summary = pd.read_sql_query("""
    SELECT "VendorNumber", SUM("Freight") AS FreightCost
    FROM vendor_invoice
    GROUP BY "VendorNumber"
""", engine)

In [31]:
freight_summary

     VendorNumber  freightcost
0            7255       648.71
1            1439         0.27
2            9751        24.53
3            6830       360.29
4            1587      6070.09
..            ...          ...
121          9625      1933.19
122          7154       432.37
123          1392     79528.99
124          1189       609.39
125         90017        80.03

[126 rows x 2 columns]

In [32]:
query = """
SELECT 
    p."VendorNumber",
    p."VendorName",
    p."Brand",
    p."PurchasePrice",
    pp."Price" AS "ActualPrice",
    pp."Volume",
    SUM(p."Quantity") AS "TotalPurchaseQuantity",
    SUM(p."Dollars") AS "TotalPurchaseDollars"
FROM purchases p
JOIN purchase_prices pp
    ON p."Brand" = pp."Brand"
WHERE p."PurchasePrice" > 0
GROUP BY 
    p."VendorNumber",
    p."VendorName",
    p."Brand",
    p."PurchasePrice",
    pp."Price",
    pp."Volume"
ORDER BY "TotalPurchaseDollars" DESC
"""

result = pd.read_sql_query(query, engine)
result

,VendorNumber,VendorName,Brand,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars
0,1128,BROWN-FORMAN CORP,1233,26.27,36.99,1750,102995.0,2705678.65
1,4425,MARTIGNETTI COMPANIES,3405,23.19,28.99,1750,115609.0,2680972.71
2,17035,PERNOD RICARD USA,8068,18.24,24.99,1750,136129.0,2482992.96
3,3960,DIAGEO NORTH AMERICA INC,3545,21.89,29.99,1750,95215.0,2084256.35
4,3960,DIAGEO NORTH AMERICA INC,4261,16.17,22.99,1750,119516.0,1932573.72
...,...,...,...,...,...,...,...,...
9892,3960,DIAGEO NORTH AMERICA INC,2626,1.42,1.99,50,2.0,2.84
9893,9815,WINE GROUP INC,8527,1.32,4.99,750,2.0,2.64
9894,8004,SAZERAC CO INC,5683,0.39,0.49,50,6.0,2.34
9895,3960,DIAGEO NORTH AMERICA INC,3775,0.73,0.99,50,1.0,0.73
9896,7245,PROXIMO SPIRITS INC.,3065,0.71,0.99,50,1.0,0.71

In [34]:
vendor_specific_sales_data.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [37]:
pd.read_sql_query("""
SELECT
    "VendorNo",
    "Brand",
    SUM(("SalesDollars")::numeric) AS TotalSalesDollars,
    SUM(("SalesPrice")::numeric) AS TotalSalesPrice,
    SUM(("SalesQuantity")::numeric) AS TotalSalesQuantity,
    SUM(("ExciseTax")::numeric) AS TotalExciseTax
FROM sales
GROUP BY "VendorNo", "Brand"
""", engine)

,VendorNo,Brand,totalsalesdollars,totalsalesprice,totalsalesquantity,totalexcisetax
0,10000,12109,5549.12,2755.57,288.0,32.06
1,10000,12110,8864.52,4231.39,548.0,61.14
2,10000,13446,77.94,38.97,6.0,0.34
3,10000,15105,26669.43,8482.02,2469.0,276.19
4,10000,17167,2759.40,1757.37,252.0,27.96
...,...,...,...,...,...,...
9220,98450,5953,919.54,639.68,46.0,18.02
9221,98450,6877,132.93,132.93,7.0,5.53
9222,98450,7890,509.83,209.93,17.0,13.39
9223,98450,8543,451.73,303.82,27.0,21.29
9224,99166,3248,3568.81,449.85,119.0,93.73

In [4]:
query = """
WITH FreightSummary AS (
    SELECT 
        "VendorNumber",
        SUM(("Freight")::numeric) AS "FreightCost"
    FROM vendor_invoice
    GROUP BY "VendorNumber"
),

PurchaseSummary AS (
    SELECT
        p."VendorNumber",
        p."VendorName",
        p."Brand",
        p."Description",
        p."PurchasePrice",
        pp."Price" AS "ActualPrice",
        pp."Volume",
        SUM((p."Quantity")::numeric) AS "TotalPurchaseQuantity",
        SUM((p."Dollars")::numeric) AS "TotalPurchaseDollars"
    FROM purchases p
    JOIN purchase_prices pp
        ON p."Brand" = pp."Brand"
    WHERE p."PurchasePrice" > 0
    GROUP BY 
        p."VendorNumber",
        p."VendorName",
        p."Brand",
        p."Description",
        p."PurchasePrice",
        pp."Price",
        pp."Volume"
),

SalesSummary AS (
    SELECT
        "VendorNo",
        "Brand",
        SUM(("SalesQuantity")::numeric) AS "TotalSalesQuantity",
        SUM(("SalesDollars")::numeric) AS "TotalSalesDollars",
        SUM(("SalesPrice")::numeric) AS "TotalSalesPrice",
        SUM(("ExciseTax")::numeric) AS "TotalExciseTax"
    FROM sales
    GROUP BY "VendorNo", "Brand"
)

SELECT
    ps."VendorNumber",
    ps."VendorName",
    ps."Brand",
    ps."Description",
    ps."PurchasePrice",
    ps."ActualPrice",
    ps."Volume",
    ps."TotalPurchaseQuantity",
    ps."TotalPurchaseDollars",
    ss."TotalSalesQuantity",
    ss."TotalSalesDollars",
    ss."TotalSalesPrice",
    ss."TotalExciseTax",
    fs."FreightCost"
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps."VendorNumber" = ss."VendorNo"::bigint   -- FIXED
    AND ps."Brand" = ss."Brand"
LEFT JOIN FreightSummary fs
    ON ps."VendorNumber" = fs."VendorNumber"
ORDER BY ps."TotalPurchaseDollars" DESC;
"""

vendor_sales_summary = pd.read_sql_query(query, engine)
vendor_sales_summary

ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: bigint = text
LINE 65:     AND ps."Brand" = ss."Brand"
                            ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[SQL:
WITH FreightSummary AS (
    SELECT
        "VendorNumber",
        SUM(("Freight")::numeric) AS "FreightCost"
    FROM vendor_invoice
    GROUP BY "VendorNumber"
),

PurchaseSummary AS (
    SELECT
        p."VendorNumber",
        p."VendorName",
        p."Brand",
        p."Description",
        p."PurchasePrice",
        pp."Price" AS "ActualPrice",
        pp."Volume",
        SUM((p."Quantity")::numeric) AS "TotalPurchaseQuantity",
        SUM((p."Dollars")::numeric) AS "TotalPurchaseDollars"
    FROM purchases p
    JOIN purchase_prices pp
        ON p."Brand" = pp."Brand"
    WHERE p."PurchasePrice" > 0
    GROUP BY
        p."VendorNumber",
        p."VendorName",
        p."Brand",
        p."Description",
        p."PurchasePrice",
        pp."Price",
        pp."Volume"
),

SalesSummary AS (
    SELECT
        "VendorNo",
        "Brand",
        SUM(("SalesQuantity")::numeric) AS "TotalSalesQuantity",
        SUM(("SalesDollars")::numeric) AS "TotalSalesDollars",
        SUM(("SalesPrice")::numeric) AS "TotalSalesPrice",
        SUM(("ExciseTax")::numeric) AS "TotalExciseTax"
    FROM sales
    GROUP BY "VendorNo", "Brand"
)

SELECT
    ps."VendorNumber",
    ps."VendorName",
    ps."Brand",
    ps."Description",
    ps."PurchasePrice",
    ps."ActualPrice",
    ps."Volume",
    ps."TotalPurchaseQuantity",
    ps."TotalPurchaseDollars",
    ss."TotalSalesQuantity",
    ss."TotalSalesDollars",
    ss."TotalSalesPrice",
    ss."TotalExciseTax",
    fs."FreightCost"
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps."VendorNumber" = ss."VendorNo"::bigint   -- FIXED
    AND ps."Brand" = ss."Brand"
LEFT JOIN FreightSummary fs
    ON ps."VendorNumber" = fs."VendorNumber"
ORDER BY ps."TotalPurchaseDollars" DESC;
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [5]:
pd.read_sql('SELECT "Brand" FROM purchases LIMIT 5', engine).dtypes

Brand    int64
dtype: object

In [6]:
pd.read_sql('SELECT "Brand" FROM sales LIMIT 5', engine).dtypes

Brand    object
dtype: object

In [10]:
query = """
WITH FreightSummary AS (
    SELECT 
        "VendorNumber",
        SUM(("Freight")::numeric) AS "FreightCost"
    FROM vendor_invoice
    GROUP BY "VendorNumber"
),

PurchaseSummary AS (
    SELECT
        p."VendorNumber",
        p."VendorName",
        p."Brand",
        p."Description",
        p."PurchasePrice",
        pp."Price" AS "ActualPrice",
        pp."Volume",
        SUM((p."Quantity")::numeric) AS "TotalPurchaseQuantity",
        SUM((p."Dollars")::numeric) AS "TotalPurchaseDollars"
    FROM purchases p
    JOIN purchase_prices pp
        ON p."Brand" = pp."Brand"
    WHERE p."PurchasePrice" > 0
    GROUP BY 
        p."VendorNumber",
        p."VendorName",
        p."Brand",
        p."Description",
        p."PurchasePrice",
        pp."Price",
        pp."Volume"
),

SalesSummary AS (
    SELECT
        "VendorNo",
        "Brand",
        SUM(("SalesQuantity")::numeric) AS "TotalSalesQuantity",
        SUM(("SalesDollars")::numeric) AS "TotalSalesDollars",
        SUM(("SalesPrice")::numeric) AS "TotalSalesPrice",
        SUM(("ExciseTax")::numeric) AS "TotalExciseTax"
    FROM sales
    GROUP BY "VendorNo", "Brand"
)

SELECT
    ps."VendorNumber",
    ps."VendorName",
    ps."Brand",
    ps."Description",
    ps."PurchasePrice",
    ps."ActualPrice",
    ps."Volume",
    ps."TotalPurchaseQuantity",
    ps."TotalPurchaseDollars",
    ss."TotalSalesQuantity",
    ss."TotalSalesDollars",
    ss."TotalSalesPrice",
    ss."TotalExciseTax",
    fs."FreightCost"
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps."VendorNumber" = ss."VendorNo"::bigint     -- FIX #1
    AND ps."Brand"::text = ss."Brand"                -- FIX #2
LEFT JOIN FreightSummary fs
    ON ps."VendorNumber" = fs."VendorNumber"
ORDER BY ps."TotalPurchaseDollars" DESC;
"""

In [11]:
vendor_sales_summary = pd.read_sql_query(query, engine)
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,102995.0,2705678.65,13360.0,479612.40,64524.20,24547.45,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,115609.0,2680972.71,15593.0,468979.95,53751.25,28650.50,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,136129.0,2482992.96,18948.0,458772.52,46584.47,34815.23,123780.22
3,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,95215.0,2084256.35,13796.0,428349.04,55916.20,25348.60,257032.07
4,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,119516.0,1932573.72,19782.0,441333.18,40914.05,36347.97,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9892,3960,DIAGEO NORTH AMERICA INC,2626,Crown Royal Apple,1.42,1.99,50,2.0,2.84,NaN,NaN,NaN,NaN,257032.07
9893,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2.0,2.64,NaN,NaN,NaN,NaN,27100.41
9894,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6.0,2.34,NaN,NaN,NaN,NaN,50293.62
9895,3960,DIAGEO NORTH AMERICA INC,3775,Smirnoff Sorbet Pine/Coconut,0.73,0.99,50,1.0,0.73,6.0,5.94,3.96,0.30,257032.07
9896,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1.0,0.71,9.0,8.91,6.93,0.46,38994.78

In [6]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                    object
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [8]:
vendor_sales_summary.isnull().sum()

VendorNumber                0
VendorName                  0
Brand                       0
Description                 0
PurchasePrice               0
ActualPrice                 0
Volume                      0
TotalPurchaseQuantity       0
TotalPurchaseDollars        0
TotalSalesQuantity       1414
TotalSalesDollars        1414
TotalSalesPrice          1414
TotalExciseTax           1414
FreightCost                 0
dtype: int64

In [9]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP          ', 'MARTIGNETTI COMPANIES',
       'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ',
       'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
       'ULTRA BEVERAGE COMPANY LLP ', 'MAJESTIC FINE WINES        ',
       'PROXIMO SPIRITS INC.       ', 'STOLI GROUP,(USA) LLC      ',
       'CAMPARI AMERICA            ', 'SAZERAC CO INC             ',
       'MOET HENNESSY USA INC      ', 'CONSTELLATION BRANDS INC   ',
       'M S WALKER INC             ', 'SAZERAC NORTH AMERICA INC. ',
       'PALM BAY INTERNATIONAL INC ', 'REMY COINTREAU USA INC     ',
       'SIDNEY FRANK IMPORTING CO  ', 'WILLIAM GRANT & SONS INC   ',
       'HEAVEN HILL DISTILLERIES   ', 'E & J GALLO WINERY         ',
       'CASTLE BRANDS CORP.        ', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS         ', 'SOUTHERN WINE & SPIRITS NE ',
       'TRINCHERO FAMILY ESTATES   ', 'STE MICHELLE WINE ESTATES  ',
       'WINE GROUP INC             ', 'MHW LTD                    ',
       'PINE STATE TRADING CO      ', 'LUXCO INC                  ',
       'TREASURY WINE ESTATES      ', 'PERFECTA WINES             ',
       'SHAW ROSS INT L IMP LTD    ', 'PHILLIPS PRODUCTS CO.      ',
       'CALEDONIA SPIRITS INC      ', 'STATE WINE & SPIRITS   ',
       'KOBRAND CORPORATION        ', 'FABRIZIA SPIRITS LLC       ',
       'VINEYARD BRANDS INC        ', 'DIAGEO CHATEAU ESTATE WINES',
       'DUGGANS DISTILLED PRODUCTS ', 'BANFI PRODUCTS CORP        ',
       'DELICATO VINEYARDS INC     ', 'Serralles Usa LLC          ',
       'OLE SMOKY DISTILLERY LLC   ', 'LAIRD & CO                 ',
       'SEA HAGG DISTILLERY LLC    ', 'KLIN SPIRITS LLC           ',
       'LATITUDE BEVERAGE COMPANY  ', 'CHARLES JACQUIN ET CIE INC ',
       'FREDERICK WILDMAN & SONS   ', 'MCCORMICK DISTILLING CO    ',
       'WESTERN SPIRITS BEVERAGE CO', 'AMERICAN VINTAGE BEVERAGE  ',
       'ADAMBA IMPORTS INTL INC    ', 'MARSALLE COMPANY           ',
       'SWEET BABY VINEYARD        ', 'Dunn Wine Brokers          ',
       'MANGO BOTTLING INC         ', 'FLAG HILL WINERY & VINEYARD',
       'VINILANDIA USA             ', 'VRANKEN AMERICA            ',
       'Russian Standard Vodka     ', 'ATLANTIC IMPORTING COMPANY ',
       'PREMIUM PORT WINES, INC.   ', 'BULLY BOY DISTILLERS       ',
       'LABELLE VYDS AND WINERY    ', 'NICHE W & S                ',
       'PREMIER DISTRIBUTORS       ', 'WEIN BAUER INC             ',
       'SMOKY QUARTZ DISTILLERY LLC', 'TAKARA SAKE USA INC        ',
       'TAMWORTH DISTILLING        ', 'PSP WINES ',
       'SEA BREEZE CELLARS LLC     ', 'ZORVINO VINEYARDS          ',
       'CRUSH WINES                ', 'TY KU LLC                  ',
       'MOONLIGHT MEADERY          ', 'STARK BREWING COMPANY      ',
       'PARK STREET IMPORTS LLC    ', 'MARTIGNETTI COMPANIES ',
       'FORTUNE WINE BROKERS LLC   ', 'POVERTY LANE ORCHARDS      ',
       'SOUTHERN GLAZERS W&S OF NE ', 'VINEXTRA INC               ',
       'TALL SHIP DISTILLERY LLC   ', 'DJINN SPIRITS LLC          ',
       'ALISA CARR BEVERAGES           ', 'JEWELL TOWNE VINEYARDS     ',
       'SWEETWATER FARM         ', 'ALTAMAR BRANDS LLC         ',
       'SURVILLE ENTERPRISES CORP  ', 'CANDIA VINEYARDS           ',
       'INCREDIBREW INC            ', 'HOOD RIVER DISTILLERS, Inc.',
       'IRA GOLDMAN AND WILLIAMS, LLP          ',
       'Circa Wines                ', 'STELLAR IMPORTING CO LLC   ',
       'VINEDREA WINES LLC         ', 'BLACK PRINCE DISTILLERY INC',
       'FULCHINO VINEYARD INC      ', 'THE IMPORTED GRAPE LLC     ',
       'STAR INDUSTRIES INC.       ', 'WALPOLE MTN VIEW WINERY    ',
       'HAUNTING WHISPER VYDS      ', 'R.P.IMPORTS INC            ',
       'GILMANTON WINERY & VINEYARD', 'THE PIERPONT GROUP LLC     ',
       'APPOLO VINEYARDS LLC       ', 'CENTEUR IMPORTS LLC        ',
       'BLACK ROCK SPIRITS LLC     ', 'AMERICAN SPIRITS EXCHANGE  ',
       'BRONCO WINE COMPANY        ', 'UNCORKED       ',
       'HIGHLAND WINE MERCHANTS LLC', 'MILTONS DISTRIBUTING CO    ',
       'TRUETT HURST               ', 'SILVER MOUNTAIN CIDERS     ',
       'FANTASY FINE WINES CORP    ', 'CAPSTONE INTERNATIONAL     '],
      dtype=object)

In [10]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')

In [11]:
vendor_sales_summary.fillna(0,inplace = True)

In [12]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [13]:
vendor_sales_summary['VendorName'].unique()

array(['BROWN-FORMAN CORP', 'MARTIGNETTI COMPANIES', 'PERNOD RICARD USA',
       'DIAGEO NORTH AMERICA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'ULTRA BEVERAGE COMPANY LLP',
       'MAJESTIC FINE WINES', 'PROXIMO SPIRITS INC.',
       'STOLI GROUP,(USA) LLC', 'CAMPARI AMERICA', 'SAZERAC CO INC',
       'MOET HENNESSY USA INC', 'CONSTELLATION BRANDS INC',
       'M S WALKER INC', 'SAZERAC NORTH AMERICA INC.',
       'PALM BAY INTERNATIONAL INC', 'REMY COINTREAU USA INC',
       'SIDNEY FRANK IMPORTING CO', 'WILLIAM GRANT & SONS INC',
       'HEAVEN HILL DISTILLERIES', 'E & J GALLO WINERY',
       'CASTLE BRANDS CORP.', 'DISARONNO INTERNATIONAL LLC',
       'EDRINGTON AMERICAS', 'SOUTHERN WINE & SPIRITS NE',
       'TRINCHERO FAMILY ESTATES', 'STE MICHELLE WINE ESTATES',
       'WINE GROUP INC', 'MHW LTD', 'PINE STATE TRADING CO', 'LUXCO INC',
       'TREASURY WINE ESTATES', 'PERFECTA WINES',
       'SHAW ROSS INT L IMP LTD', 'PHILLIPS PRODUCTS CO.',
       'CALEDONIA SPIRITS INC', 'STATE WINE & SPIRITS',
       'KOBRAND CORPORATION', 'FABRIZIA SPIRITS LLC',
       'VINEYARD BRANDS INC', 'DIAGEO CHATEAU ESTATE WINES',
       'DUGGANS DISTILLED PRODUCTS', 'BANFI PRODUCTS CORP',
       'DELICATO VINEYARDS INC', 'Serralles Usa LLC',
       'OLE SMOKY DISTILLERY LLC', 'LAIRD & CO',
       'SEA HAGG DISTILLERY LLC', 'KLIN SPIRITS LLC',
       'LATITUDE BEVERAGE COMPANY', 'CHARLES JACQUIN ET CIE INC',
       'FREDERICK WILDMAN & SONS', 'MCCORMICK DISTILLING CO',
       'WESTERN SPIRITS BEVERAGE CO', 'AMERICAN VINTAGE BEVERAGE',
       'ADAMBA IMPORTS INTL INC', 'MARSALLE COMPANY',
       'SWEET BABY VINEYARD', 'Dunn Wine Brokers', 'MANGO BOTTLING INC',
       'FLAG HILL WINERY & VINEYARD', 'VINILANDIA USA', 'VRANKEN AMERICA',
       'Russian Standard Vodka', 'ATLANTIC IMPORTING COMPANY',
       'PREMIUM PORT WINES, INC.', 'BULLY BOY DISTILLERS',
       'LABELLE VYDS AND WINERY', 'NICHE W & S', 'PREMIER DISTRIBUTORS',
       'WEIN BAUER INC', 'SMOKY QUARTZ DISTILLERY LLC',
       'TAKARA SAKE USA INC', 'TAMWORTH DISTILLING', 'PSP WINES',
       'SEA BREEZE CELLARS LLC', 'ZORVINO VINEYARDS', 'CRUSH WINES',
       'TY KU LLC', 'MOONLIGHT MEADERY', 'STARK BREWING COMPANY',
       'PARK STREET IMPORTS LLC', 'FORTUNE WINE BROKERS LLC',
       'POVERTY LANE ORCHARDS', 'SOUTHERN GLAZERS W&S OF NE',
       'VINEXTRA INC', 'TALL SHIP DISTILLERY LLC', 'DJINN SPIRITS LLC',
       'ALISA CARR BEVERAGES', 'JEWELL TOWNE VINEYARDS',
       'SWEETWATER FARM', 'ALTAMAR BRANDS LLC',
       'SURVILLE ENTERPRISES CORP', 'CANDIA VINEYARDS', 'INCREDIBREW INC',
       'HOOD RIVER DISTILLERS, Inc.', 'IRA GOLDMAN AND WILLIAMS, LLP',
       'Circa Wines', 'STELLAR IMPORTING CO LLC', 'VINEDREA WINES LLC',
       'BLACK PRINCE DISTILLERY INC', 'FULCHINO VINEYARD INC',
       'THE IMPORTED GRAPE LLC', 'STAR INDUSTRIES INC.',
       'WALPOLE MTN VIEW WINERY', 'HAUNTING WHISPER VYDS',
       'R.P.IMPORTS INC', 'GILMANTON WINERY & VINEYARD',
       'THE PIERPONT GROUP LLC', 'APPOLO VINEYARDS LLC',
       'CENTEUR IMPORTS LLC', 'BLACK ROCK SPIRITS LLC',
       'AMERICAN SPIRITS EXCHANGE', 'BRONCO WINE COMPANY', 'UNCORKED',
       'HIGHLAND WINE MERCHANTS LLC', 'MILTONS DISTRIBUTING CO',
       'TRUETT HURST', 'SILVER MOUNTAIN CIDERS',
       'FANTASY FINE WINES CORP', 'CAPSTONE INTERNATIONAL'], dtype=object)

In [14]:
vendor_sales_summary.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesDollars        0
TotalSalesPrice          0
TotalExciseTax           0
FreightCost              0
dtype: int64

In [15]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                   float64
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [16]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']

In [17]:
vendor_sales_summary['GrossProfit'].min()

-2226066.25

In [18]:
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalSalesDollars'])*100

In [19]:
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']

In [20]:
vendor_sales_summary['SalesPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [21]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("""
        CREATE TABLE vendor_sales_summary (
            VendorNumber BIGINT,
            VendorName VARCHAR(100),
            Brand BIGINT,
            Description VARCHAR(200),
            PurchasePrice DECIMAL(15,2),
            ActualPrice DECIMAL(15,2),
            Volume DECIMAL(15,2),
            TotalPurchaseQuantity INT,
            TotalPurchaseDollars DECIMAL(15,2),
            TotalSalesQuantity DECIMAL(15,2),
            TotalSalesDollars DECIMAL(15,2),
            TotalSalesPrice DECIMAL(15,2),
            TotalExciseTax DECIMAL(15,2),
            FreightCost DECIMAL(15,2),
            GrossProfit DECIMAL(15,2),
            ProfitMargin DECIMAL(15,2),
            StockTurnover DECIMAL(15,2),
            SalesToPurchaseRatio DECIMAL(15,2),
            PRIMARY KEY (VendorNumber, Brand)
        );
    """))

In [22]:
pd.read_sql_query("select * from vendor_sales_summary",engine)

ProgrammingError: (psycopg2.errors.UndefinedTable) relation "vendor_sales_summary" does not exist
LINE 1: select * from vendor_sales_summary
                      ^

[SQL: select * from vendor_sales_summary]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [23]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE vendor_sales_summary (
            VendorNumber BIGINT,
            VendorName VARCHAR(100),
            Brand BIGINT,
            Description VARCHAR(200),
            PurchasePrice DECIMAL(15,2),
            ActualPrice DECIMAL(15,2),
            Volume DECIMAL(15,2),
            TotalPurchaseQuantity INT,
            TotalPurchaseDollars DECIMAL(15,2),
            TotalSalesQuantity DECIMAL(15,2),
            TotalSalesDollars DECIMAL(15,2),
            TotalSalesPrice DECIMAL(15,2),
            TotalExciseTax DECIMAL(15,2),
            FreightCost DECIMAL(15,2),
            GrossProfit DECIMAL(15,2),
            ProfitMargin DECIMAL(15,2),
            StockTurnover DECIMAL(15,2),
            SalesToPurchaseRatio DECIMAL(15,2),
            PRIMARY KEY (VendorNumber, Brand)
        );
    """))

In [24]:
pd.read_sql_query("SELECT * FROM vendor_sales_summary", engine)

Empty DataFrame
Columns: [vendornumber, vendorname, brand, description, purchaseprice, actualprice, volume, totalpurchasequantity, totalpurchasedollars, totalsalesquantity, totalsalesdollars, totalsalesprice, totalexcisetax, freightcost, grossprofit, profitmargin, stockturnover, salestopurchaseratio]
Index: []

In [25]:
vendor_sales_summary.to_sql(
    "vendor_sales_summary",
    engine,
    if_exists="append",
    index=False
)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "VendorNumber" of relation "vendor_sales_summary" does not exist
LINE 1: INSERT INTO vendor_sales_summary ("VendorNumber", "VendorNam...
                                          ^

[SQL: INSERT INTO vendor_sales_summary ("VendorNumber", "VendorName", "Brand", "Description", "PurchasePrice", "ActualPrice", "Volume", "TotalPurchaseQuantity", "TotalPurchaseDollars", "TotalSalesQuantity", "TotalSalesDollars", "TotalSalesPrice", "TotalExc ... 436019 characters truncated ... s, %(GrossProfit__999)s, %(ProfitMargin__999)s, %(StockTurnover__999)s, %(SalesPurchaseRatio__999)s)]
[parameters: {'TotalExciseTax__0': 24547.45, 'ActualPrice__0': 36.99, 'ProfitMargin__0': -464.1385939979867, 'TotalPurchaseDollars__0': 2705678.65, 'TotalSalesQuantity__0': 13360.0, 'StockTurnover__0': 0.12971503471042284, 'Brand__0': 1233, 'SalesPurchaseRatio__0': 0.1772614053779077, 'Volume__0': 1750.0, 'FreightCost__0': 68601.68, 'VendorNumber__0': 1128, 'TotalPurchaseQuantity__0': 102995.0, 'PurchasePrice__0': 26.27, 'VendorName__0': 'BROWN-FORMAN CORP', 'TotalSalesPrice__0': 64524.2, 'GrossProfit__0': -2226066.25, 'TotalSalesDollars__0': 479612.4, 'Description__0': 'Jack Daniels No 7 Black', 'TotalExciseTax__1': 28650.5, 'ActualPrice__1': 28.99, 'ProfitMargin__1': -471.66041106874604, 'TotalPurchaseDollars__1': 2680972.71, 'TotalSalesQuantity__1': 15593.0, 'StockTurnover__1': 0.13487704244479237, 'Brand__1': 3405, 'SalesPurchaseRatio__1': 0.1749290279049502, 'Volume__1': 1750.0, 'FreightCost__1': 144929.24, 'VendorNumber__1': 4425, 'TotalPurchaseQuantity__1': 115609.0, 'PurchasePrice__1': 23.19, 'VendorName__1': 'MARTIGNETTI COMPANIES', 'TotalSalesPrice__1': 53751.25, 'GrossProfit__1': -2211992.76, 'TotalSalesDollars__1': 468979.95, 'Description__1': "Tito's Handmade Vodka", 'TotalExciseTax__2': 34815.23, 'ActualPrice__2': 24.99, 'ProfitMargin__2': -441.22530268377886, 'TotalPurchaseDollars__2': 2482992.96, 'TotalSalesQuantity__2': 18948.0, 'StockTurnover__2': 0.13919150217808107, 'Brand__2': 8068, 'SalesPurchaseRatio__2': 0.18476593667023528, 'Volume__2': 1750.0, 'FreightCost__2': 123780.22, 'VendorNumber__2': 17035, 'TotalPurchaseQuantity__2': 136129.0, 'PurchasePrice__2': 18.24, 'VendorName__2': 'PERNOD RICARD USA' ... 17900 parameters truncated ... 'TotalSalesQuantity__997': 875.0, 'StockTurnover__997': 0.1498800959232614, 'Brand__997': 35442, 'SalesPurchaseRatio__997': 0.2526863144946023, 'Volume__997': 750.0, 'FreightCost__997': 55551.82, 'VendorNumber__997': 9552, 'TotalPurchaseQuantity__997': 5838.0, 'PurchasePrice__997': 8.21, 'VendorName__997': 'M S WALKER INC', 'TotalSalesPrice__997': 5219.27, 'GrossProfit__997': -35818.73, 'TotalSalesDollars__997': 12111.25, 'Description__997': 'Borsao Tres Picos Garnacha', 'TotalExciseTax__998': 132.13, 'ActualPrice__998': 13.99, 'ProfitMargin__998': -208.61350072627837, 'TotalPurchaseDollars__998': 47910.24, 'TotalSalesQuantity__998': 1185.0, 'StockTurnover__998': 0.1679421768707483, 'Brand__998': 26732, 'SalesPurchaseRatio__998': 0.32402989423555384, 'Volume__998': 750.0, 'FreightCost__998': 68054.7, 'VendorNumber__998': 9165, 'TotalPurchaseQuantity__998': 7056.0, 'PurchasePrice__998': 6.79, 'VendorName__998': 'ULTRA BEVERAGE COMPANY LLP', 'TotalSalesPrice__998': 7034.87, 'GrossProfit__998': -32385.89, 'TotalSalesDollars__998': 15524.35, 'Description__998': 'Bonterra Cab Svgn Organic', 'TotalExciseTax__999': 312.28, 'ActualPrice__999': 21.99, 'ProfitMargin__999': -425.0032880171503, 'TotalPurchaseDollars__999': 47901.51, 'TotalSalesQuantity__999': 396.0, 'StockTurnover__999': 0.1316927169936814, 'Brand__999': 3999, 'SalesPurchaseRatio__999': 0.19047499755226924, 'Volume__999': 750.0, 'FreightCost__999': 123880.97, 'VendorNumber__999': 12546, 'TotalPurchaseQuantity__999': 3007.0, 'PurchasePrice__999': 15.93, 'VendorName__999': 'JIM BEAM BRANDS COMPANY', 'TotalSalesPrice__999': 7280.85, 'GrossProfit__999': -38777.47, 'TotalSalesDollars__999': 9124.04, 'Description__999': 'Hornitos Anejo Tequila'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [26]:
pd.read_sql_query("""
SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'vendor_sales_summary';
""", engine)

              column_name
0    salestopurchaseratio
1           stockturnover
2            vendornumber
3                   brand
4           purchaseprice
5             actualprice
6                  volume
7   totalpurchasequantity
8    totalpurchasedollars
9      totalsalesquantity
10      totalsalesdollars
11        totalsalesprice
12         totalexcisetax
13            freightcost
14            grossprofit
15           profitmargin
16             vendorname
17            description

In [27]:
with engine.begin() as conn:
    conn.execute(text('DROP TABLE IF EXISTS vendor_sales_summary;'))

In [28]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE vendor_sales_summary (
            VendorNumber BIGINT,
            VendorName VARCHAR(100),
            Brand BIGINT,
            Description VARCHAR(200),
            PurchasePrice DECIMAL(15,2),
            ActualPrice DECIMAL(15,2),
            Volume DECIMAL(15,2),
            TotalPurchaseQuantity INT,
            TotalPurchaseDollars DECIMAL(15,2),
            TotalSalesQuantity DECIMAL(15,2),
            TotalSalesDollars DECIMAL(15,2),
            TotalSalesPrice DECIMAL(15,2),
            TotalExciseTax DECIMAL(15,2),
            FreightCost DECIMAL(15,2),
            GrossProfit DECIMAL(15,2),
            ProfitMargin DECIMAL(15,2),
            StockTurnover DECIMAL(15,2),
            SalesToPurchaseRatio DECIMAL(15,2),
            PRIMARY KEY (VendorNumber, Brand)
        );
    """))

In [30]:
vendor_sales_summary.to_sql(
    "vendor_sales_summary",
    engine,
    if_exists="append",
    index=False
)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "VendorNumber" of relation "vendor_sales_summary" does not exist
LINE 1: INSERT INTO vendor_sales_summary ("VendorNumber", "VendorNam...
                                          ^

[SQL: INSERT INTO vendor_sales_summary ("VendorNumber", "VendorName", "Brand", "Description", "PurchasePrice", "ActualPrice", "Volume", "TotalPurchaseQuantity", "TotalPurchaseDollars", "TotalSalesQuantity", "TotalSalesDollars", "TotalSalesPrice", "TotalExc ... 436019 characters truncated ... s, %(GrossProfit__999)s, %(ProfitMargin__999)s, %(StockTurnover__999)s, %(SalesPurchaseRatio__999)s)]
[parameters: {'TotalExciseTax__0': 24547.45, 'ActualPrice__0': 36.99, 'ProfitMargin__0': -464.1385939979867, 'TotalPurchaseDollars__0': 2705678.65, 'TotalSalesQuantity__0': 13360.0, 'StockTurnover__0': 0.12971503471042284, 'Brand__0': 1233, 'SalesPurchaseRatio__0': 0.1772614053779077, 'Volume__0': 1750.0, 'FreightCost__0': 68601.68, 'VendorNumber__0': 1128, 'TotalPurchaseQuantity__0': 102995.0, 'PurchasePrice__0': 26.27, 'VendorName__0': 'BROWN-FORMAN CORP', 'TotalSalesPrice__0': 64524.2, 'GrossProfit__0': -2226066.25, 'TotalSalesDollars__0': 479612.4, 'Description__0': 'Jack Daniels No 7 Black', 'TotalExciseTax__1': 28650.5, 'ActualPrice__1': 28.99, 'ProfitMargin__1': -471.66041106874604, 'TotalPurchaseDollars__1': 2680972.71, 'TotalSalesQuantity__1': 15593.0, 'StockTurnover__1': 0.13487704244479237, 'Brand__1': 3405, 'SalesPurchaseRatio__1': 0.1749290279049502, 'Volume__1': 1750.0, 'FreightCost__1': 144929.24, 'VendorNumber__1': 4425, 'TotalPurchaseQuantity__1': 115609.0, 'PurchasePrice__1': 23.19, 'VendorName__1': 'MARTIGNETTI COMPANIES', 'TotalSalesPrice__1': 53751.25, 'GrossProfit__1': -2211992.76, 'TotalSalesDollars__1': 468979.95, 'Description__1': "Tito's Handmade Vodka", 'TotalExciseTax__2': 34815.23, 'ActualPrice__2': 24.99, 'ProfitMargin__2': -441.22530268377886, 'TotalPurchaseDollars__2': 2482992.96, 'TotalSalesQuantity__2': 18948.0, 'StockTurnover__2': 0.13919150217808107, 'Brand__2': 8068, 'SalesPurchaseRatio__2': 0.18476593667023528, 'Volume__2': 1750.0, 'FreightCost__2': 123780.22, 'VendorNumber__2': 17035, 'TotalPurchaseQuantity__2': 136129.0, 'PurchasePrice__2': 18.24, 'VendorName__2': 'PERNOD RICARD USA' ... 17900 parameters truncated ... 'TotalSalesQuantity__997': 875.0, 'StockTurnover__997': 0.1498800959232614, 'Brand__997': 35442, 'SalesPurchaseRatio__997': 0.2526863144946023, 'Volume__997': 750.0, 'FreightCost__997': 55551.82, 'VendorNumber__997': 9552, 'TotalPurchaseQuantity__997': 5838.0, 'PurchasePrice__997': 8.21, 'VendorName__997': 'M S WALKER INC', 'TotalSalesPrice__997': 5219.27, 'GrossProfit__997': -35818.73, 'TotalSalesDollars__997': 12111.25, 'Description__997': 'Borsao Tres Picos Garnacha', 'TotalExciseTax__998': 132.13, 'ActualPrice__998': 13.99, 'ProfitMargin__998': -208.61350072627837, 'TotalPurchaseDollars__998': 47910.24, 'TotalSalesQuantity__998': 1185.0, 'StockTurnover__998': 0.1679421768707483, 'Brand__998': 26732, 'SalesPurchaseRatio__998': 0.32402989423555384, 'Volume__998': 750.0, 'FreightCost__998': 68054.7, 'VendorNumber__998': 9165, 'TotalPurchaseQuantity__998': 7056.0, 'PurchasePrice__998': 6.79, 'VendorName__998': 'ULTRA BEVERAGE COMPANY LLP', 'TotalSalesPrice__998': 7034.87, 'GrossProfit__998': -32385.89, 'TotalSalesDollars__998': 15524.35, 'Description__998': 'Bonterra Cab Svgn Organic', 'TotalExciseTax__999': 312.28, 'ActualPrice__999': 21.99, 'ProfitMargin__999': -425.0032880171503, 'TotalPurchaseDollars__999': 47901.51, 'TotalSalesQuantity__999': 396.0, 'StockTurnover__999': 0.1316927169936814, 'Brand__999': 3999, 'SalesPurchaseRatio__999': 0.19047499755226924, 'Volume__999': 750.0, 'FreightCost__999': 123880.97, 'VendorNumber__999': 12546, 'TotalPurchaseQuantity__999': 3007.0, 'PurchasePrice__999': 15.93, 'VendorName__999': 'JIM BEAM BRANDS COMPANY', 'TotalSalesPrice__999': 7280.85, 'GrossProfit__999': -38777.47, 'TotalSalesDollars__999': 9124.04, 'Description__999': 'Hornitos Anejo Tequila'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [31]:
pd.read_sql_query("""
SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'vendor_sales_summary';
""", engine)

              column_name
0    salestopurchaseratio
1           stockturnover
2            vendornumber
3                   brand
4           purchaseprice
5             actualprice
6                  volume
7   totalpurchasequantity
8    totalpurchasedollars
9      totalsalesquantity
10      totalsalesdollars
11        totalsalesprice
12         totalexcisetax
13            freightcost
14            grossprofit
15           profitmargin
16             vendorname
17            description

In [32]:
with engine.begin() as conn:
    conn.execute(text('DROP TABLE IF EXISTS vendor_sales_summary;'))

In [33]:
pd.read_sql_query("""
SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'vendor_sales_summary';
""", engine)

Empty DataFrame
Columns: [column_name]
Index: []

In [34]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE vendor_sales_summary (
            VendorNumber BIGINT,
            VendorName VARCHAR(100),
            Brand BIGINT,
            Description VARCHAR(200),
            PurchasePrice DECIMAL(15,2),
            ActualPrice DECIMAL(15,2),
            Volume DECIMAL(15,2),
            TotalPurchaseQuantity INT,
            TotalPurchaseDollars DECIMAL(15,2),
            TotalSalesQuantity DECIMAL(15,2),
            TotalSalesDollars DECIMAL(15,2),
            TotalSalesPrice DECIMAL(15,2),
            TotalExciseTax DECIMAL(15,2),
            FreightCost DECIMAL(15,2),
            GrossProfit DECIMAL(15,2),
            ProfitMargin DECIMAL(15,2),
            StockTurnover DECIMAL(15,2),
            SalesToPurchaseRatio DECIMAL(15,2),
            PRIMARY KEY (VendorNumber, Brand)
        );
    """))

In [3]:
pd.read_sql_query("""
SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'vendor_sales_summary';
""", engine)

              column_name
0    salestopurchaseratio
1           stockturnover
2            vendornumber
3                   brand
4           purchaseprice
5             actualprice
6                  volume
7   totalpurchasequantity
8    totalpurchasedollars
9      totalsalesquantity
10      totalsalesdollars
11        totalsalesprice
12         totalexcisetax
13            freightcost
14            grossprofit
15           profitmargin
16             vendorname
17            description

In [5]:
from sqlalchemy import text
with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS vendor_sales_summary;"))

In [6]:
pd.read_sql_query("""
SELECT table_name 
FROM information_schema.tables 
WHERE table_name = 'vendor_sales_summary';
""", engine)

Empty DataFrame
Columns: [table_name]
Index: []

In [7]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE vendor_sales_summary (
            "VendorNumber" BIGINT,
            "VendorName" VARCHAR(100),
            "Brand" BIGINT,
            "Description" VARCHAR(200),
            "PurchasePrice" DECIMAL(15,2),
            "ActualPrice" DECIMAL(15,2),
            "Volume" DECIMAL(15,2),
            "TotalPurchaseQuantity" INT,
            "TotalPurchaseDollars" DECIMAL(15,2),
            "TotalSalesQuantity" DECIMAL(15,2),
            "TotalSalesDollars" DECIMAL(15,2),
            "TotalSalesPrice" DECIMAL(15,2),
            "TotalExciseTax" DECIMAL(15,2),
            "FreightCost" DECIMAL(15,2),
            "GrossProfit" DECIMAL(15,2),
            "ProfitMargin" DECIMAL(15,2),
            "StockTurnover" DECIMAL(15,2),
            "SalesToPurchaseRatio" DECIMAL(15,2),
            PRIMARY KEY ("VendorNumber", "Brand")
        );
    """))

In [8]:
pd.read_sql_query("""
SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'vendor_sales_summary';
""", engine)

              column_name
0    SalesToPurchaseRatio
1           StockTurnover
2            VendorNumber
3                   Brand
4           PurchasePrice
5             ActualPrice
6                  Volume
7   TotalPurchaseQuantity
8    TotalPurchaseDollars
9      TotalSalesQuantity
10      TotalSalesDollars
11        TotalSalesPrice
12         TotalExciseTax
13            FreightCost
14            GrossProfit
15           ProfitMargin
16             VendorName
17            Description

In [12]:
vendor_sales_summary.to_sql(
    "vendor_sales_summary",
    engine,
    if_exists="append",
    index=False
)

897

In [13]:
pd.read_sql_query("SELECT * FROM vendor_sales_summary", engine)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,102995,2705678.65,13360.0,479612.40,64524.20,24547.45,68601.68,None,None,None,None
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,115609,2680972.71,15593.0,468979.95,53751.25,28650.50,144929.24,None,None,None,None
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,136129,2482992.96,18948.0,458772.52,46584.47,34815.23,123780.22,None,None,None,None
3,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,95215,2084256.35,13796.0,428349.04,55916.20,25348.60,257032.07,None,None,None,None
4,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,119516,1932573.72,19782.0,441333.18,40914.05,36347.97,257032.07,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9892,3960,DIAGEO NORTH AMERICA INC,2626,Crown Royal Apple,1.42,1.99,50.0,2,2.84,NaN,NaN,NaN,NaN,257032.07,None,None,None,None
9893,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,NaN,NaN,NaN,NaN,27100.41,None,None,None,None
9894,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,NaN,NaN,NaN,NaN,50293.62,None,None,None,None
9895,3960,DIAGEO NORTH AMERICA INC,3775,Smirnoff Sorbet Pine/Coconut,0.73,0.99,50.0,1,0.73,6.0,5.94,3.96,0.30,257032.07,None,None,None,None
9896,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,9.0,8.91,6.93,0.46,38994.78,None,None,None,None

In [5]:
import pandas as pd
import logging
import traceback
from datetime import datetime
from sqlalchemy import create_engine, text

# =====================================================
# 1. SETUP LOGGING WITH TIMESTAMPED FILE
# =====================================================
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
log_filename = f"logs/get_vendor_summary_{timestamp}.log"

logging.basicConfig(
    filename=log_filename,
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s - %(message)s",
    filemode="a"
)

logging.info(f"Log file created: {log_filename}")

# =====================================================
# 2. DATABASE CONNECTION
# =====================================================
DATABASE_URL = "postgresql+psycopg2://postgres:akasmik@localhost:5432/Inventory_vendor"
engine = create_engine(DATABASE_URL)


# =====================================================
# 3. CREATE MAIN TABLE IF NOT EXISTS
# =====================================================
def create_vendor_summary_table():
    try:
        logging.info("Creating vendor_sales_summary table if not exists...")

        create_table_sql = text("""
        CREATE TABLE IF NOT EXISTS vendor_sales_summary (
            "VendorNumber" BIGINT,
            "VendorName" VARCHAR(100),
            "Brand" BIGINT,
            "Description" VARCHAR(200),
            "PurchasePrice" DECIMAL(15,2),
            "ActualPrice" DECIMAL(15,2),
            "Volume" DECIMAL(15,2),
            "TotalPurchaseQuantity" DECIMAL(15,2),
            "TotalPurchaseDollars" DECIMAL(15,2),
            "TotalSalesQuantity" DECIMAL(15,2),
            "TotalSalesDollars" DECIMAL(15,2),
            "TotalSalesPrice" DECIMAL(15,2),
            "TotalExciseTax" DECIMAL(15,2),
            "FreightCost" DECIMAL(15,2),
            "GrossProfit" DECIMAL(15,2),
            "ProfitMargin" DECIMAL(15,2),
            "StockTurnover" DECIMAL(15,2),
            "SalesToPurchaseRatio" DECIMAL(15,2),
            PRIMARY KEY ("VendorNumber", "Brand")
        );
        """)

        with engine.begin() as conn:
            conn.execute(create_table_sql)

        logging.info("Table creation check complete.")

    except Exception as e:
        logging.error("Error creating vendor_sales_summary table.")
        logging.error(traceback.format_exc())
        raise e


# =====================================================
# 4. RUN SQL SUMMARY QUERY
# =====================================================
def create_vendor_summary():
    try:
        logging.info("Running SQL summary query...")

        query = """
        WITH FreightSummary AS (
            SELECT 
                "VendorNumber",
                SUM(("Freight")::numeric) AS "FreightCost"
            FROM vendor_invoice
            GROUP BY "VendorNumber"
        ),

        PurchaseSummary AS (
            SELECT
                p."VendorNumber",
                p."VendorName",
                p."Brand",
                p."Description",
                p."PurchasePrice",
                pp."Price" AS "ActualPrice",
                pp."Volume",
                SUM((p."Quantity")::numeric) AS "TotalPurchaseQuantity",
                SUM((p."Dollars")::numeric) AS "TotalPurchaseDollars"
            FROM purchases p
            JOIN purchase_prices pp
                ON p."Brand"::text = pp."Brand"::text
            WHERE p."PurchasePrice" > 0
            GROUP BY 
                p."VendorNumber", p."VendorName", p."Brand",
                p."Description", p."PurchasePrice", pp."Price", pp."Volume"
        ),

        SalesSummary AS (
            SELECT
                "VendorNo"::bigint AS "VendorNumber",
                "Brand",
                SUM(("SalesQuantity")::numeric) AS "TotalSalesQuantity",
                SUM(("SalesDollars")::numeric) AS "TotalSalesDollars",
                SUM(("SalesPrice")::numeric) AS "TotalSalesPrice",
                SUM(("ExciseTax")::numeric) AS "TotalExciseTax"
            FROM sales
            GROUP BY "VendorNo", "Brand"
        )

        SELECT
            ps."VendorNumber",
            ps."VendorName",
            ps."Brand",
            ps."Description",
            ps."PurchasePrice",
            ps."ActualPrice",
            ps."Volume",
            ps."TotalPurchaseQuantity",
            ps."TotalPurchaseDollars",
            ss."TotalSalesQuantity",
            ss."TotalSalesDollars",
            ss."TotalSalesPrice",
            ss."TotalExciseTax",
            fs."FreightCost"
        FROM PurchaseSummary ps
        LEFT JOIN SalesSummary ss
            ON ps."VendorNumber" = ss."VendorNumber"
            AND ps."Brand"::text = ss."Brand"::text
        LEFT JOIN FreightSummary fs
            ON ps."VendorNumber" = fs."VendorNumber"
        ORDER BY ps."TotalPurchaseDollars" DESC;
        """

        df = pd.read_sql_query(query, engine)
        logging.info("SQL summary query executed successfully.")
        return df

    except Exception as e:
        logging.error("Error executing vendor summary SQL.")
        logging.error(traceback.format_exc())
        raise e


# =====================================================
# 5. CLEAN DATA
# =====================================================
def clean_data(df):
    try:
        logging.info("Cleaning data...")

        df["Volume"] = df["Volume"].astype(float)
        df.fillna(0, inplace=True)

        df["VendorName"] = df["VendorName"].astype(str).str.strip()
        df["Description"] = df["Description"].astype(str).str.strip()

        df["GrossProfit"] = df["TotalSalesDollars"] - df["TotalPurchaseDollars"]
        df["ProfitMargin"] = (df["GrossProfit"] / df["TotalSalesDollars"].replace(0, 1)) * 100
        df["StockTurnover"] = df["TotalSalesQuantity"] / df["TotalPurchaseQuantity"].replace(0, 1)
        df["SalesToPurchaseRatio"] = df["TotalSalesDollars"] / df["TotalPurchaseDollars"].replace(0, 1)

        logging.info("Data cleaning completed.")
        return df

    except Exception as e:
        logging.error("Error cleaning data.")
        logging.error(traceback.format_exc())
        raise e


# =====================================================
# 6. SAFE UPSERT INTO POSTGRESQL
# =====================================================
def insert_into_database(df):
    """
    Inserts DataFrame safely using a staging table + UPSERT.
    Avoids huge multi-row inserts and avoids PK conflicts.
    """
    try:
        logging.info("Starting safe upsert from staging table...")

        staging_table = "vendor_sales_summary_stage"

        # 1. Write staging table (replace)
        logging.info(f"Writing staging table '{staging_table}'...")
        df.to_sql(
            staging_table,
            engine,
            if_exists="replace",
            index=False,
            method="multi",
            chunksize=500
        )

        logging.info("Staging table written. Executing UPSERT...")

        cols = [
            "VendorNumber", "VendorName", "Brand", "Description", "PurchasePrice", "ActualPrice", "Volume",
            "TotalPurchaseQuantity", "TotalPurchaseDollars", "TotalSalesQuantity", "TotalSalesDollars",
            "TotalSalesPrice", "TotalExciseTax", "FreightCost", "GrossProfit", "ProfitMargin",
            "StockTurnover", "SalesToPurchaseRatio"
        ]

        quoted_cols = ", ".join(f'"{c}"' for c in cols)

        update_assignments = ", ".join(
            f'"{c}" = EXCLUDED."{c}"' for c in cols if c not in ("VendorNumber", "Brand")
        )

        upsert_sql = f"""
        INSERT INTO vendor_sales_summary ({quoted_cols})
        SELECT {quoted_cols}
        FROM {staging_table}
        ON CONFLICT ("VendorNumber", "Brand") DO UPDATE
        SET {update_assignments};
        
        DROP TABLE IF EXISTS {staging_table};
        """

        with engine.begin() as conn:
            conn.execute(text(upsert_sql))

        logging.info("UPSERT completed successfully.")

    except Exception as e:
        logging.error("Error during database UPSERT.")
        logging.error(traceback.format_exc())

        # cleanup staging table
        try:
            with engine.begin() as conn:
                conn.execute(text(f"DROP TABLE IF EXISTS {staging_table};"))
        except:
            logging.warning("Failed to drop staging table during cleanup.")

        raise e


# =====================================================
# 7. MAIN PIPELINE
# =====================================================
def main():
    try:
        logging.info("Pipeline started...")

        create_vendor_summary_table()
        df = create_vendor_summary()
        df = clean_data(df)
        insert_into_database(df)

        logging.info("Pipeline completed successfully.")

    except Exception as e:
        logging.critical("Pipeline failed!")
        logging.critical(traceback.format_exc())
        print("Pipeline failed. Check log file for details:", log_filename)


# =====================================================
# 8. RUN SCRIPT
# =====================================================
if __name__ == "__main__":
    main()